# Repository Configuration
# Use this file as a reference for configuring repository settings

# Branch Protection Rules for 'main' branch
# Configure via GitHub UI: Settings > Branches > Add rule

required_status_checks:
  - "security-scan"
  - "test-matrix"
  - "browser-test" 
  - "package-integrity"
  - "code-quality"

required_pull_request_reviews:
  required_approving_review_count: 1
  dismiss_stale_reviews: true
  require_code_owner_reviews: true
  require_last_push_approval: false

enforce_admins: true
allow_force_pushes: false
allow_deletions: false
block_creations: false

# Required GitHub Repository Settings
settings:
  # General
  - delete_branch_on_merge: true
  - merge_commit_title: "PR_TITLE"
  - merge_commit_message: "PR_BODY"
  - squash_merge_commit_title: "PR_TITLE"
  - squash_merge_commit_message: "PR_BODY"
  
  # Features
  - has_issues: true
  - has_projects: true
  - has_wiki: false
  - has_discussions: true
  
  # Security
  - allow_merge_commit: true
  - allow_squash_merge: true
  - allow_rebase_merge: false
  - delete_branch_on_merge: true

# Security & Analysis Settings
security:
  # Enable in repository settings
  - dependency_graph: true
  - dependabot_alerts: true
  - dependabot_security_updates: true
  - code_scanning_default_setup: true
  - secret_scanning: true
  - secret_scanning_push_protection: true

# Required Repository Secrets
# Add these in Settings > Secrets and variables > Actions
secrets:
  - SEMGREP_APP_TOKEN: "optional token for enhanced Semgrep scanning"
  # NPM_TOKEN not needed - publishing is manual

# Collaborators and Teams
# Configure in Settings > Manage access
collaborators:
  - username: "draeder"
    permission: "admin"
  # Add team reviewers as needed
  # - team: "security-team" 
  #   permission: "write"

# Topics/Tags for repository discovery
topics:
  - "cryptography"
  - "javascript"
  - "nodejs" 
  - "browser"
  - "webcrypto"
  - "encryption"
  - "digital-signatures"
  - "security"
  - "p256"
  - "ecdsa"
  - "ecdh"
  - "aes-gcm"
